name: branchname

on:
  push:
    branches:
      - fea1
jobs:
#   set-env:
#     runs-on: ubuntu-latest
#     steps:

 GET-ENV:
       name: "Polaris-Get ENV"
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - name: run build
           shell: bash
           run: |
             echo "GIT_BRANCH=$(echo '${{github.ref}}' | awk -F '/' '{print $3}')" >> $GITHUB_ENV
             echo $GIT_BRANCH
         - name: Read exported variable
           run: |
             echo "$abbr"
             echo "${{ env.GIT_BRANCH }}"
               
#  Polaris-SAST-Scan:
#     needs: GET-ENV
#     name: "Polaris-SAST Scan for merge to: ${{GITHUB_REF}} "
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout the repository
#         uses: actions/checkout@v1
