name: branchname

on:
  push:
    branches:
      - fea1
jobs:
#   set-env:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Set environment variables
#         run: |
#           echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
#           echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
#       - name: Use environment variables
#         run: |
#           echo "GIT_SHA=${GIT_SHA}"
#           echo "GIT_BRANCH=${GIT_BRANCH}"
 GET-ENV:
       name: "Polaris-Get ENV"
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - name: run build
#            run: |
#              echo "::set-env name=GITHUB_REF::${{ github.ref }}"
#              echo "old GITHUB_REF is $GITHUB_REF"
#              GITHUB_REF=$(echo $GITHUB_REF | sed -e "s#refs/heads/##g")
#              echo "new GITHUB_REF is $GITHUB_REF"
           run: |
             echo "BRANCH_NAME=$(echo ${{ github.ref }} | cut -d'/' -f 3)" >> $GITHUB_ENV
             echo $BRANCH_NAME 
  
#  Polaris-SAST-Scan:
#     needs: GET-ENV
#     name: "Polaris-SAST Scan for merge to: ${{GITHUB_REF}} "
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout the repository
#         uses: actions/checkout@v1
