name: branchname

on:
  push:
    branches:
      - dev


jobs:
  job1:
   name: "Polaris-SAST Scan for merge to:"
   runs-on: ubuntu-latest
   steps:
   - name: Set the value
     id: step_one
     run: |
        echo "BR_NAME= $(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
   - name: Use the value
     id: step_two
     run: |
        echo "${{ env.BR_NAME }}" # This will output 'yellow'
   - name: Debug
     run: echo ${{ env.BR_NAME }}
  job2:
    name: "Polaris-SAST"
    #${{ github.ref }} 
    #$(echo $GITHUB_REF | cut -d'/' -f 3)
    runs-on: ubuntu-latest
    steps:
#       - name: Get branch name (merge)
#         if: github.event_name != 'pull_request'
#         shell: bash
#         run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BR_NAME= $(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

      - name: "Polaris-SAST Scan for merge to:  ${{ env.BRANCH_NAME }}"
        run: echo ${{ env.BRANCH_NAME }}        

#   name: "job1"
#   runs-on: ubuntu-latest
#   steps:
#   - name: "setting the variabel name"
#     shell: bash
#     run: |
#      echo "BR_NAME= $(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
#   - name: Debug
#     run: echo ${{ env.BR_NAME }}


    
    
